#springboot的多环境配置：可以选择激活哪个配置文件
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test

---
server:
  port: 8883
spring:
  profiles: te
